### ISSUE TITLE
Cannot destructure property `range` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by capaj** [OnlyLys/Leaper#3]
```
  ERR Cannot destructure property `range` of 'undefined' or 'null'.: TypeError: Cannot destructure property `range` of 'undefined' or 'null'.
    at checkForNewPair (/home/capaj/.vscode/extensions/onlylys.leaper-0.5.3/out/pairs.js:257:43)
    at Pairs.updateGivenContentChanges (/home/capaj/.vscode/extensions/onlylys.leaper-0.5.3/out/pairs.js:108:25)
    at __dirname.constructor.contentChangeWatcher.vscode_1.workspace.onDidChangeTextDocument.event (/home/capaj/.vscode/extensions/onlylys.leaper-0.5.3/out/controller.js:24:24)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at e.$acceptDirtyStateChanged (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:538:777)
    at e.$acceptModelSaved (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:538:531)
    at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
    at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
    at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
    at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

this seems to happen in almost any file

**Comment by crystalfp** [comment]
Yes! Confirm. It happens also to me with latest release (0.5.3)

**Comment by OnlyLys** [comment]
Sorry I've been away for a while I'll look into this right away

Edit: Sorry this had to come so late. I had a look at it and I wasn't able to reproduce the issue at all. Are you still having the same problem? 

I'm currently writing a brand new implementation of the extension which should hopefully sidestep this problem altogether. I'll push the update out ASAP.

**Comment by disco0** [comment]
Still getting this—it seems that content changes can zero length?
![image](https://user-images.githubusercontent.com/13393582/120184407-cdc6ad80-c1c5-11eb-8988-6da2706e295d.png)

**Comment by djfm** [comment]
Confirmed, and it messes up the imports sometimes badly.

**Comment by OnlyLys** [comment]
@djfm Hey I'll look into it again and get back to you ASAP.

**Comment by OnlyLys** [comment]
@djfm Apologies for the long delay but I've finally managed to update the extension by merging over 2 years of code into the master branch. Please let me know if you're still having issues.

**Comment by OnlyLys** [comment]
I encourage anyone who is still having problems with this to open a new issue.
